name: Node.js CI Build-Release-Deploy

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: install deps
        run: npm ci
      - name: build
        run: make build
      - name: package for deployment
        run: make deb

      - name: debugging info
        run: |
          ls -lh
          echo "----"
          ls -lh dist

      - name: get deployment package name
        run: echo "DEB_NAME=$(basename dist/inventorius-frontend_*_all.deb)" >> $GITHUB_ENV
      - name: upload deployment artifact
        uses: actions/upload-artifact@v2
        with:
          name: inventorius-frontend_latest_all.deb
          path: dist/${{ env.DEB_NAME }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"

      - name: Release tag range
        if: ${{ !contains(github.ref, '-')}}
        run: |
          echo TO_TAG=$(git tag | tr - \~ | sort -V | tr \~ - | tail -n 1) >> $GITHUB_ENV
          echo FROM_TAG=$(git tag | tr - \~ | sort -V | tr \~ - | grep -v '-' | tail -n 2 | head -n 1) >> $GITHUB_ENV
      - name: Prerelease tag range
        if: ${{ contains(github.ref, '-')}}
        run: |
          echo TO_TAG=$(git tag | tr - \~ | sort -V | tr \~ - | tail -n 1) >> $GITHUB_ENV
          echo FROM_TAG=$(git tag | tr - \~ | sort -V | tr \~ - | tail -n 2 | head -n 1) >> $GITHUB_ENV

      - name: debug
        env:
          FROM_TAG: ${{ env.FROM_TAG }}
          TO_TAG: ${{ env.TO_TAG }}
        run: echo $FROM_TAG .. $TO_TAG

      - name: Build changelog
        id: build_changelog
        uses: scottbrenner/generate-changelog-action@master
        with:
          from-tag: ${{ env.FROM_TAG }}
          to-tag: ${{ env.TO_TAG }}

      - name: get deployment package
        uses: actions/download-artifact@v2
        with:
          name: inventorius-frontend_latest_all.deb

      - name: debug output
        run: ls -lh

      - name: Get tag name
        run: |
          echo $GITHUB_REF
          echo ${GITHUB_REF#refs/tags/}
          echo TAG_NAME=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      
      - name: get deployment package name
        run: echo "DEB_NAME=$(basename inventorius-frontend_*_all.deb)" >> $GITHUB_ENV

      - name: Create prerelease
        if: ${{contains(github.ref, '-')}}
        uses: softprops/action-gh-release@v1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          files: ${{ env.DEB_NAME }}
          name: Prerelease ${{ env.TAG_NAME }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: true

      - name: Create release
        if: ${{!contains(github.ref, '-')}}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          files: inventorius-frontend_latest_all.deb
          name: Release ${{ env.TAG_NAME }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup private key
        env:
          PRIVKEYENCRYPTED: ${{ secrets.DEPLOY_PRIVKEY_GPG_PASSWORD }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PRIVKEYENCRYPTED" --output github_id_rsa deployment-ci/github_id_rsa.gpg
          chmod 600 github_id_rsa
      - name: get deployment package
        uses: actions/download-artifact@v2
        with:
          name: inventorius-frontend_latest_all.deb

      - name: get deployment package name
        run: echo "DEB_NAME=$(basename inventorius-frontend_*_all.deb)" >> $GITHUB_ENV

      - name: upload deployment package
        run: scp -i github_id_rsa -o UserKnownHostsFile=deployment-ci/known_hosts $DEB_NAME root@computemachines.com:$DEB_NAME
        env:
          DEB_NAME: ${{ env.DEB_NAME }}

      - name: Run deployment commands on production server
        run: |
          ssh -T -i github_id_rsa -o UserKnownHostsFile=deployment-ci/known_hosts root@computemachines.com dpkg -i $DEB_NAME
        env:
          DEB_NAME: ${{ env.DEB_NAME }}
